#! /bin/bash
# fix brightness panasonic

if [[ $(id -u) != 0 ]]; then
    echo >&2 "Root permission required."
    exit 1
fi

vendor="/sys/class/backlight/panasonic"
intel="/sys/class/backlight/intel_backlight"
maxVendor=$(cat $vendor/max_brightness)
maxIntel=$(cat $intel/max_brightness)

while (true); do
    vendorAct=$(cat $vendor/actual_brightness)
    intelAct=$(( maxIntel * vendorAct / maxVendor ))
    echo $intelAct | tee $intel/brightness
done
